name: subtitle_wrapper_package
description: A Subtitle Wrapper package, this subtitle wrapper package displays subtitles for a video player.
version: 1.0.2
homepage: https://github.com/Joran-Dob/flutter_subtitle_wrapper

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Custom video player with custom loadControl for exoplayer
  video_player: #^1.0.0
    git:
      url: https://github.com/ayush221b/plugins.git
      path: packages/video_player/video_player
      ref: f93cfee154c0eea639276669f72283fe9db5b2a9

  http: ^0.12.0+2
  bloc: ^6.0.0
  flutter_bloc: ^6.0.0
  equatable: ^1.2.0
  http_parser: ^3.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
